// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFL6d0RwyOT_xJ_wmhMJXDzFPwf0SdQXQ',
    appId: '1:826710647401:web:245a07dccce99a118538f8',
    messagingSenderId: '826710647401',
    projectId: 'ecolife-d6f17',
    authDomain: 'ecolife-d6f17.firebaseapp.com',
    storageBucket: 'ecolife-d6f17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrF0l6QBemU3deUlvGVOKxP3yht05pGpQ',
    appId: '1:826710647401:android:f7932167e35aa55d8538f8',
    messagingSenderId: '826710647401',
    projectId: 'ecolife-d6f17',
    storageBucket: 'ecolife-d6f17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNswz5WzK79ooIES41HrlSu3BCllFngg4',
    appId: '1:826710647401:ios:ec511be5b3ddb09c8538f8',
    messagingSenderId: '826710647401',
    projectId: 'ecolife-d6f17',
    storageBucket: 'ecolife-d6f17.firebasestorage.app',
    iosBundleId: 'com.example.ecolife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNswz5WzK79ooIES41HrlSu3BCllFngg4',
    appId: '1:826710647401:ios:ec511be5b3ddb09c8538f8',
    messagingSenderId: '826710647401',
    projectId: 'ecolife-d6f17',
    storageBucket: 'ecolife-d6f17.firebasestorage.app',
    iosBundleId: 'com.example.ecolife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFL6d0RwyOT_xJ_wmhMJXDzFPwf0SdQXQ',
    appId: '1:826710647401:web:be74b8605efd277b8538f8',
    messagingSenderId: '826710647401',
    projectId: 'ecolife-d6f17',
    authDomain: 'ecolife-d6f17.firebaseapp.com',
    storageBucket: 'ecolife-d6f17.firebasestorage.app',
  );
}
